name: Run test suite
on: push

jobs:
    
  run-test:
    name: Php Unit test
    runs-on: ubuntu-latest
    
    container:
      image: composer-latest
      volumes:
        - myapp:app
    steps:
      - name: Run composer 
        run: composer instamm
      - name: Run php Unit
        run: ./vendor/bin/phpunit test #test direcoty in this project
