name: Run test suite
on: push

jobs:
    
  run-test:
    name: Php Unit test
    runs-on: ubuntu-latest
    
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout using github action
        uses: actions/checkout@v2
      - name: Run composer 
        run: composer install
      - name: Run php Unit
        run: ./vendor/bin/phpunit tests #test direcoty in this project
